### PR TITLE
Add security related best practices

### PR DESCRIPTION
**Pull request by w13915984028**
JIRA ticket SURE-8222
GH issue: TBD

### CODE REVIEW

**Review by jillian-maroket — COMMENTED** [review]
Initial review done

**Review by tserong — COMMENTED** [review]
Content looks reasonable to me :-)

**Comment by ibrokethecloud** [comment]
sorry @w13915984028 took me a while to get around to this. If we could please incorporate the feedback from @jillian-maroket then we can get this merged.

**Review by ibrokethecloud — APPROVED** [review]
lgtm. thanks.

**Review by jillian-maroket — APPROVED** [review]

**Pull request merged**
